export const ROOM_INITIAL_VALUES = {
  name: "",
  roomType: "",
  roomNumber: "",
  description: "",
  images: [],
  price: "",
  roomSize: "",
  totalBeds: "",
  bedTypes: [{ type: "", quantity: "" }],
  sofaBed: false,
  extraBedAvailable: false,
  sameConfigForRemainingBeds: false,
  maxGuests: "",
  maxAdults: "",
  maxChildren: "",
  hasBalcony: false,
  bathroomType: "",
  rating: "",
  tags: [""],
  amenities: [""],
  isSmokingAllowed: false,
  housekeepingFrequency: "",
};
